project_name: translate
builds:
  - env: [CGO_ENABLED=0]
    main: ./go/main.go
    goos:
      - windows
    goarch:
      - amd64
archives:
  - format_overrides:
    - goos: windows
      format: zip
