project_name: translate
builds:
  - env: [CGO_ENABLED=0]
    main: ./go/main.go
    goos:
      - windows
    goarch:
      - amd64
    # ldflags を指定する
    ldflags:
      - -H windowsgui -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
archives:
  - format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE*
      - README*
      - ahk/translate.ahk
