name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  ahkbuild:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with AHK v2 latest
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: "v2.0.10"
          x64: true
          x86: false
          compression: upx
          in: ahk
          out: ahk-build
      - name: debug
        run:
          pwd
          ls -R ahk-build
      # - name: Upload build directory
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ahk-build
      #     path: $env:GITHUB_WORKSPACE\ahk-build
  # goreleaser:
  #   runs-on: ubuntu-latest
  #   needs: ahkbuild
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - run: git fetch --force --tags
  #     - name: Setup Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.21'
  #     - name: Run Go Tests
  #       run: GOOS=windows GOARCH=amd64 go test -v ./...
  #     - name: Generate GitHub Apps token
  #       id: generate
  #       uses: tibdex/github-app-token@v1
  #       with:
  #         app_id: ${{ secrets.APP_ID }}
  #         private_key: ${{ secrets.PRIVATE_KEY }}
  #     - name: download build directory
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ahk-build
  #         path: $GIT_WORKSPACE/ahk-build
  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v5
  #       with:
  #         # either 'goreleaser' (default) or 'goreleaser-pro':
  #         distribution: goreleaser
  #         version: latest
  #         args: release --clean
  #       env:
  #         GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
