name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  ahkbuild:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with AHK v2 latest
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: "v2.0.10"
          x64: true
          x86: false
          compression: upx
          in: ahk
          out: build
      - name: move exe to workspace
        shell: pwsh
        run: |
          cp build/*.exe $env:GITHUB_WORKSPACE
      - name: debug
        shell: pwsh
        run: |
          ls build
          ls $env:GITHUB_WORKSPACE
  goreleaser:
    runs-on: ubuntu-latest
    needs: ahkbuild
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run Go Tests
        run: GOOS=windows GOARCH=amd64 go test -v ./...
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: debug workspace
        run: |
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/build
      - name: copy ahk exe from workspace
        run: |
          cp $GITHUB_WORKSPACE/*.exe .
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
